import SideNavbar from "@/components/personnel-page/SideNavbar/SideNavbar";
import "../globals.css";
import { Nunito } from "next/font/google";
import { options } from "@/app/api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/providers/SessionProvider/SessionProvider";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

const newFont = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <div
      className={newFont.className}
      style={{ position: "relative", backgroundColor: "var(--color-1)" }}
    >
      {(session?.user.role === "ADMIN" ||
        session?.user.role === "PERSONNEL") && (
        <SessionProvider>
          <SideNavbar />
        </SessionProvider>
      )}
      {children}
    </div>
  );
}
