import "../globals.css";
import { Nunito } from "next/font/google";
import SideNavbar from "@/components/admin-page/SideNavbar/SideNavbar";
import { options } from "@/app/api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import QueryProvider from "@/components/providers/QueryProvider/QueryProvider";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

const newFont = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <div
      className={newFont.className}
      style={{ position: "relative", backgroundColor: "var(--color-1)" }}
    >
      {session?.user.role === "ADMIN" && <SideNavbar />}
      <QueryProvider>{children}</QueryProvider>
    </div>
  );
}
