import "../globals.css";
import { Nunito } from "next/font/google";
import SideNavbar from "@/components/admin-page/SideNavbar/SideNavbar";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

const newFont = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body
        className={newFont.className}
        style={{ position: "relative", backgroundColor: "var(--color-1)" }}
      >
        <SideNavbar />
        {children}
      </body>
    </html>
  );
}
