import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import UIContextProvier from "@/context/uiControl";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

const newFont = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body
        className={newFont.className}
        style={{ position: "relative", backgroundColor: "#dedede" }}
      >
        <UIContextProvier>
          <Navbar />
        </UIContextProvier>
        {children}
        <Footer />
      </body>
    </html>
  );
}
