import "../globals.css";
import { Nunito } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import UIContextProvier from "@/context/uiControl";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/ui/scroll-to-top/ScrollToTop";
import SessionProvider from "@/components/providers/SessionProvider/SessionProvider";
import DashboardButton from "@/components/main/DashboardButton/DashboardButton";

export const metadata = {
  title: "Physical Therapy",
  description: "Generated by create next app",
};

const newFont = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={newFont.className}
      style={{ position: "relative", backgroundColor: "var(--color-1)" }}
    >
      <SessionProvider>
        <UIContextProvier>
          <Navbar />
          <DashboardButton />
        </UIContextProvier>
      </SessionProvider>
      {children}
      <Footer />
      <ScrollToTop />
    </div>
  );
}
