import "../globals.css";
import { Nunito } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import UIContextProvier from "@/context/uiControl";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/ui/scroll-to-top/ScrollToTop";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

const newFont = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body
        className={newFont.className}
        style={{ position: "relative", backgroundColor: "var(--color-1)" }}
      >
        <ToastContainer
          position="top-right"
          autoClose={2000}
          limit={2}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <UIContextProvier>
          <Navbar />
        </UIContextProvier>
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
